version: '3.8'
services:
  fe-app-admin:
    image: fe-container:admin
    ports:
      - 81:81
    depends_on:
      - nest-app
    networks:
      - common-network
  fe-app-user:
    image: fe-container:user
    ports:
      - 80:80
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/shiyanchen/Applications/remote-mysql-docker-mounted-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/shiyanchen/Applications/redis-docker-mounted-data:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
